[env:waveshare_lcd_21]
extra_scripts = pre:cnext_build.py
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
