#ifndef CAN_BUS_H
#define CAN_BUS_H

/**
 * Generated by C-Next Transpiler from: can_bus.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <J1939Message.hpp>
#include "j1939_decoder.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void CanBus_init(void);
void CanBus_poll(void);

#ifdef __cplusplus
}
#endif

#endif /* CAN_BUS_H */
