#ifndef J1939_DECODER_H
#define J1939_DECODER_H

/**
 * Generated by C-Next Transpiler from: j1939_decoder.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "signal_data.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void J1939Decoder_decode(uint16_t pgn, const uint8_t data[8]);

#ifdef __cplusplus
}
#endif

#endif /* J1939_DECODER_H */
