#ifndef SIGNAL_DATA_H
#define SIGNAL_DATA_H

/**
 * Generated by C-Next Transpiler from: signal_data.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Signal {
    float value;
    uint32_t time;
} Signal;
typedef struct SignalData {
    Signal ambient_temp_c;
    Signal barometric_pressure_kpa;
    Signal relative_humidity_pct;
    Signal egt_c;
    Signal oil_temp_c;
    Signal fuel_pressure_kpa;
    Signal rpm;
    Signal total_dist_km;
} SignalData;

/* External variables */
extern const uint32_t SIGNAL_STALE_MS;
extern SignalData SignalStore_current;

#ifdef __cplusplus
}
#endif

#endif /* SIGNAL_DATA_H */
