#ifndef SIGNAL_DATA_H
#define SIGNAL_DATA_H

/**
 * Generated by C-Next Transpiler from: signal_data.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Signal {
    float value;
    uint32_t time;
} Signal;
typedef struct GearState {
    uint8_t lever;
    uint8_t demanded;
    uint8_t actual;
    uint32_t time;
} GearState;
typedef struct Status {
    uint8_t state;
    uint32_t time;
} Status;
typedef struct SignalData {
    Signal ambient_temp_c;
    Signal barometric_pressure_kpa;
    Signal relative_humidity_pct;
    Signal egt_c;
    Signal oil_temp_c;
    Signal fuel_pressure_kpa;
    Signal boost_kpa;
    Signal throttle_pct;
    Signal engine_load_pct;
    Signal turbo_mcu_temp_c;
    Signal rpm;
    Signal total_dist_km;
    GearState gear;
    Signal trans_temp_c;
    Status tow_haul;
    Status trans_service;
    Status trans_warning;
} SignalData;

/* External variables */
extern const uint32_t SIGNAL_STALE_MS;
extern SignalData SignalStore_current;

#ifdef __cplusplus
}
#endif

#endif /* SIGNAL_DATA_H */
