#ifndef TWAI_DRIVER_H
#define TWAI_DRIVER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <J1939Message.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void TwaiDriver_init(void);
void TwaiDriver_poll(void);

#ifdef __cplusplus
}
#endif

#endif /* TWAI_DRIVER_H */
