/**
 * Generated by C-Next Transpiler from: display_st7701.cnx
 * A safer C for embedded systems
 */

#include "display_st7701.hpp"

#include "tca9554.hpp"
#include <Arduino.h>
#include <driver/spi_master.h>
#include <esp_lcd_types.h>
#include <esp_lcd_panel_ops.h>
#include <esp_lcd_panel_rgb.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: Display */
static spi_device_handle_t Display_spi_handle = {};
static esp_lcd_panel_handle_t Display_panel_handle = {};

static void Display_spi_cmd(uint8_t cmd) {
    struct spi_transaction_t txn = (spi_transaction_t){ .cmd = 0, .addr = cmd, .length = 0, .rxlength = 0 };
    spi_device_transmit(Display_spi_handle, &txn);
}

static void Display_spi_data(uint8_t data) {
    struct spi_transaction_t txn = (spi_transaction_t){ .cmd = 1, .addr = data, .length = 0, .rxlength = 0 };
    spi_device_transmit(Display_spi_handle, &txn);
}

static void Display_cs_enable(void) {
    TCA9554_set_pin(3, false);
    vTaskDelay(pdMS_TO_TICKS(10));
}

static void Display_cs_disable(void) {
    TCA9554_set_pin(3, true);
    vTaskDelay(pdMS_TO_TICKS(10));
}

static void Display_reset(void) {
    TCA9554_set_pin(1, false);
    vTaskDelay(pdMS_TO_TICKS(10));
    TCA9554_set_pin(1, true);
    vTaskDelay(pdMS_TO_TICKS(50));
}

static void Display_spi_init(void) {
    spi_bus_config_t buscfg = (spi_bus_config_t){ .mosi_io_num = 1, .miso_io_num = -1, .sclk_io_num = 2, .quadwp_io_num = -1, .quadhd_io_num = -1, .max_transfer_sz = 64 };
    spi_bus_initialize(SPI2_HOST, &buscfg, SPI_DMA_CH_AUTO);
    spi_device_interface_config_t devcfg = (spi_device_interface_config_t){ .command_bits = 1, .address_bits = 8, .mode = 0, .clock_speed_hz = 40000000, .spics_io_num = -1, .queue_size = 1 };
    spi_bus_add_device(SPI2_HOST, &devcfg, &Display_spi_handle);
}

static void Display_st7701_init(void) {
    Display_cs_enable();
    Display_spi_cmd(0xFFU);
    Display_spi_data(0x77U);
    Display_spi_data(0x01U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x10U);
    Display_spi_cmd(0xC0U);
    Display_spi_data(0x3BU);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xC1U);
    Display_spi_data(0x0BU);
    Display_spi_data(0x02U);
    Display_spi_cmd(0xC2U);
    Display_spi_data(0x07U);
    Display_spi_data(0x02U);
    Display_spi_cmd(0xCCU);
    Display_spi_data(0x10U);
    Display_spi_cmd(0xCDU);
    Display_spi_data(0x08U);
    Display_spi_cmd(0xB0U);
    Display_spi_data(0x00U);
    Display_spi_data(0x11U);
    Display_spi_data(0x16U);
    Display_spi_data(0x0eU);
    Display_spi_data(0x11U);
    Display_spi_data(0x06U);
    Display_spi_data(0x05U);
    Display_spi_data(0x09U);
    Display_spi_data(0x08U);
    Display_spi_data(0x21U);
    Display_spi_data(0x06U);
    Display_spi_data(0x13U);
    Display_spi_data(0x10U);
    Display_spi_data(0x29U);
    Display_spi_data(0x31U);
    Display_spi_data(0x18U);
    Display_spi_cmd(0xB1U);
    Display_spi_data(0x00U);
    Display_spi_data(0x11U);
    Display_spi_data(0x16U);
    Display_spi_data(0x0eU);
    Display_spi_data(0x11U);
    Display_spi_data(0x07U);
    Display_spi_data(0x05U);
    Display_spi_data(0x09U);
    Display_spi_data(0x09U);
    Display_spi_data(0x21U);
    Display_spi_data(0x05U);
    Display_spi_data(0x13U);
    Display_spi_data(0x11U);
    Display_spi_data(0x2aU);
    Display_spi_data(0x31U);
    Display_spi_data(0x18U);
    Display_spi_cmd(0xFFU);
    Display_spi_data(0x77U);
    Display_spi_data(0x01U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x11U);
    Display_spi_cmd(0xB0U);
    Display_spi_data(0x6dU);
    Display_spi_cmd(0xB1U);
    Display_spi_data(0x37U);
    Display_spi_cmd(0xB2U);
    Display_spi_data(0x81U);
    Display_spi_cmd(0xB3U);
    Display_spi_data(0x80U);
    Display_spi_cmd(0xB5U);
    Display_spi_data(0x43U);
    Display_spi_cmd(0xB7U);
    Display_spi_data(0x85U);
    Display_spi_cmd(0xB8U);
    Display_spi_data(0x20U);
    Display_spi_cmd(0xC1U);
    Display_spi_data(0x78U);
    Display_spi_cmd(0xC2U);
    Display_spi_data(0x78U);
    Display_spi_cmd(0xD0U);
    Display_spi_data(0x88U);
    Display_spi_cmd(0xE0U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x02U);
    Display_spi_cmd(0xE1U);
    Display_spi_data(0x03U);
    Display_spi_data(0xA0U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x04U);
    Display_spi_data(0xA0U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x20U);
    Display_spi_data(0x20U);
    Display_spi_cmd(0xE2U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xE3U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x11U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xE4U);
    Display_spi_data(0x22U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xE5U);
    Display_spi_data(0x05U);
    Display_spi_data(0xECU);
    Display_spi_data(0xA0U);
    Display_spi_data(0xA0U);
    Display_spi_data(0x07U);
    Display_spi_data(0xEEU);
    Display_spi_data(0xA0U);
    Display_spi_data(0xA0U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xE6U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x11U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xE7U);
    Display_spi_data(0x22U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xE8U);
    Display_spi_data(0x06U);
    Display_spi_data(0xEDU);
    Display_spi_data(0xA0U);
    Display_spi_data(0xA0U);
    Display_spi_data(0x08U);
    Display_spi_data(0xEFU);
    Display_spi_data(0xA0U);
    Display_spi_data(0xA0U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xEBU);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x40U);
    Display_spi_data(0x40U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0xEDU);
    Display_spi_data(0xFFU);
    Display_spi_data(0xFFU);
    Display_spi_data(0xFFU);
    Display_spi_data(0xBAU);
    Display_spi_data(0x0AU);
    Display_spi_data(0xBFU);
    Display_spi_data(0x45U);
    Display_spi_data(0xFFU);
    Display_spi_data(0xFFU);
    Display_spi_data(0x54U);
    Display_spi_data(0xFBU);
    Display_spi_data(0xA0U);
    Display_spi_data(0xABU);
    Display_spi_data(0xFFU);
    Display_spi_data(0xFFU);
    Display_spi_data(0xFFU);
    Display_spi_cmd(0xEFU);
    Display_spi_data(0x10U);
    Display_spi_data(0x0DU);
    Display_spi_data(0x04U);
    Display_spi_data(0x08U);
    Display_spi_data(0x3FU);
    Display_spi_data(0x1FU);
    Display_spi_cmd(0xFFU);
    Display_spi_data(0x77U);
    Display_spi_data(0x01U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x13U);
    Display_spi_cmd(0xEFU);
    Display_spi_data(0x08U);
    Display_spi_cmd(0xFFU);
    Display_spi_data(0x77U);
    Display_spi_data(0x01U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0x36U);
    Display_spi_data(0x00U);
    Display_spi_cmd(0x3AU);
    Display_spi_data(0x66U);
    Display_spi_cmd(0x11U);
    vTaskDelay(pdMS_TO_TICKS(480));
    Display_spi_cmd(0x20U);
    vTaskDelay(pdMS_TO_TICKS(120));
    Display_spi_cmd(0x29U);
    Display_cs_disable();
}

static void Display_rgb_panel_init(void) {
    esp_lcd_rgb_panel_config_t rgb_config = (esp_lcd_rgb_panel_config_t){ .clk_src = LCD_CLK_SRC_PLL160M, .timings = (esp_lcd_rgb_timing_t){ .pclk_hz = 16000000, .h_res = 480, .v_res = 480, .hsync_pulse_width = 8, .hsync_back_porch = 10, .hsync_front_porch = 50, .vsync_pulse_width = 3, .vsync_back_porch = 8, .vsync_front_porch = 8 }, .data_width = 16, .psram_trans_align = 64, .hsync_gpio_num = 38, .vsync_gpio_num = 39, .de_gpio_num = 40, .pclk_gpio_num = 41, .data_gpio_nums = {5, 45, 48, 47, 21, 14, 13, 12, 11, 10, 9, 46, 3, 8, 18, 17}, .disp_gpio_num = -1 };
    rgb_config.flags.fb_in_psram = true;
    esp_lcd_new_rgb_panel(&rgb_config, &Display_panel_handle);
    esp_lcd_panel_reset(Display_panel_handle);
    esp_lcd_panel_init(Display_panel_handle);
}

static void Display_backlight_init(void) {
    ledcSetup(0, 20000, 10);
    ledcAttachPin(6, 0);
    ledcWrite(0, 500);
}

void Display_init(void) {
    Display_reset();
    Display_spi_init();
    Display_st7701_init();
    Display_rgb_panel_init();
    Display_backlight_init();
}

void Display_fill_color(uint16_t color) {
    uint16_t buf[480] = {0};
    uint32_t i = 0U;
    while (i < 480) {
        buf[i] = color;
        i = i + 1U;
    }
    i = 0U;
    while (i < 480) {
        esp_lcd_panel_draw_bitmap(Display_panel_handle, 0, i, 480, i + 1, buf);
        i = i + 1U;
    }
}

esp_lcd_panel_handle_t Display_get_panel(void) {
    return Display_panel_handle;
}
