/**
 * Generated by C-Next Transpiler from: gauge_trans.cnx
 * A safer C for embedded systems
 */

#include "display/gauge_trans.hpp"

#include <Arduino.h>
#include <lvgl.h>
#include "../data/signal_data.hpp"

#include <stdint.h>

/* Scope: GaugeTrans */
static lv_obj_t* GaugeTrans_gear_val = NULL;

static uint8_t GaugeTrans_gear_char(uint8_t raw) {
    uint8_t result = static_cast<uint8_t>('0');
    if (raw == 0xFF) {
        result = static_cast<uint8_t>('-');
    }
    if (raw == 0xFE) {
        result = static_cast<uint8_t>('-');
    }
    if (raw < 0xFE) {
        int32_t g = ((raw) & 0xFFU);
        g = g - 125;
        if (g >= 1 && g <= 9) {
            int32_t cv = 48 + g;
            result = static_cast<uint8_t>(((cv) & 0xFFU));
        }
        if (g <= -1 && g >= -9) {
            result = static_cast<uint8_t>('R');
        }
    }
    return result;
}

static uint8_t GaugeTrans_lever_char(uint8_t raw) {
    uint8_t result = raw;
    if (raw <= 0x20) {
        result = static_cast<uint8_t>('-');
    }
    if (raw == 0x36) {
        result = static_cast<uint8_t>('D');
    }
    return result;
}

void GaugeTrans_update(void) {
    uint32_t now = millis();
    uint32_t age = now - SignalStore_current.gear.time;
    if (age > SIGNAL_STALE_MS) {
        lv_label_set_text(GaugeTrans_gear_val, "-  -  -");
    } else {
        uint8_t lv = GaugeTrans_lever_char(SignalStore_current.gear.lever);
        uint8_t dm = GaugeTrans_gear_char(SignalStore_current.gear.demanded);
        uint8_t ac = GaugeTrans_gear_char(SignalStore_current.gear.actual);
        lv_label_set_text_fmt(GaugeTrans_gear_val, "%c  %c  %c", lv, dm, ac);
    }
}

static void GaugeTrans_on_update_timer(lv_timer_t* t) {
    GaugeTrans_update();
}

void GaugeTrans_create(void) {
    lv_obj_t* scr = lv_screen_active();
    GaugeTrans_gear_val = lv_label_create(scr);
    lv_label_set_text(GaugeTrans_gear_val, "-  -  -");
    lv_obj_align(GaugeTrans_gear_val, LV_ALIGN_CENTER, 0, 180);
    lv_obj_set_style_text_font(GaugeTrans_gear_val, &lv_font_montserrat_40, LV_PART_MAIN);
    lv_obj_set_style_text_color(GaugeTrans_gear_val, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_timer_create(GaugeTrans_on_update_timer, 100, 0);
}
