/**
 * Generated by C-Next Transpiler from: i2c_driver.cnx
 * A safer C for embedded systems
 */

#include "display/i2c_driver.hpp"

#include <Wire.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: I2C */

void I2C_init(void) {
    Wire.begin(15, 7);
}

uint8_t I2C_read_byte(uint8_t addr, uint8_t reg) {
    Wire.beginTransmission(addr);
    Wire.write(reg);
    uint8_t err = Wire.endTransmission(true);
    if (err != 0) {
        printf("I2C read failed\r\n");
        return 0;
    }
    Wire.requestFrom(addr, 1);
    return Wire.read();
}

bool I2C_write_byte(uint8_t addr, uint8_t reg, uint8_t data) {
    Wire.beginTransmission(addr);
    Wire.write(reg);
    Wire.write(data);
    uint8_t err = Wire.endTransmission(true);
    if (err != 0) {
        printf("I2C write failed\r\n");
        return false;
    }
    return true;
}
