/**
 * Generated by C-Next Transpiler from: touch_cst820.cnx
 * A safer C for embedded systems
 */

#include "display/touch_cst820.hpp"

#include "tca9554.hpp"
#include <Arduino.h>
#include <Wire.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: Touch */
static uint8_t Touch_points = 0;
static uint16_t Touch_x = 0;
static uint16_t Touch_y = 0;

static void Touch_reset(void) {
    TCA9554_set_pin(2, false);
    delay(10);
    TCA9554_set_pin(2, true);
    delay(50);
}

void Touch_init(void) {
    Touch_reset();
    I2C_write_byte(0x15, 0xFE, 0xFF);
    Serial.println("Touch: CST820 initialized");
}

bool Touch_read(void) {
    Wire.beginTransmission(0x15);
    Wire.write(0x01);
    Wire.endTransmission(false);
    Wire.requestFrom(0x15, 6);
    uint8_t gesture = Wire.read();
    Touch_points = Wire.read();
    uint8_t x_hi = Wire.read();
    uint8_t x_lo = Wire.read();
    uint8_t y_hi = Wire.read();
    uint8_t y_lo = Wire.read();
    Touch_x = (uint16_t)((Touch_x & ~(0xFFU << 0)) | ((x_lo & 0xFFU) << 0));
    Touch_x = (uint16_t)((Touch_x & ~(0xFFU << 8)) | ((((x_hi) & ((1U << 4) - 1)) & 0xFFU) << 8));
    Touch_y = (uint16_t)((Touch_y & ~(0xFFU << 0)) | ((y_lo & 0xFFU) << 0));
    Touch_y = (uint16_t)((Touch_y & ~(0xFFU << 8)) | ((((y_hi) & ((1U << 4) - 1)) & 0xFFU) << 8));
    return (Touch_points > 0);
}

uint16_t Touch_get_x(void) {
    return Touch_x;
}

uint16_t Touch_get_y(void) {
    return Touch_y;
}
