#ifndef DISPLAY_ST7701_H
#define DISPLAY_ST7701_H

/**
 * Generated by C-Next Transpiler from: display_st7701.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "tca9554.hpp"
#include <esp_lcd_types.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Display_init(void);
void Display_fill_color(uint16_t color);
esp_lcd_panel_handle_t Display_get_panel(void);

#ifdef __cplusplus
}
#endif

#endif /* DISPLAY_ST7701_H */
