#ifndef GAUGE_SPEED_H
#define GAUGE_SPEED_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void GaugeSpeed_create(void);

#ifdef __cplusplus
}
#endif

#endif /* GAUGE_SPEED_H */
