#ifndef TOUCH_CST820_H
#define TOUCH_CST820_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "tca9554.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Touch_init(void);
bool Touch_read(void);
uint16_t Touch_get_x(void);
uint16_t Touch_get_y(void);

#ifdef __cplusplus
}
#endif

#endif /* TOUCH_CST820_H */
