#ifndef DISPLAY_ST7701_H
#define DISPLAY_ST7701_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "tca9554.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Display_init(void);
void Display_fill_color(uint16_t color);

#ifdef __cplusplus
}
#endif

#endif /* DISPLAY_ST7701_H */
