/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "display_st7701.h"

#include "tca9554.h"
#include <Arduino.h>
#include <driver/spi_master.h>
#include <esp_lcd_panel_ops.h>
#include <esp_lcd_panel_rgb.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: Display */
static spi_device_handle_t Display_spi_handle = {};
static esp_lcd_panel_handle_t Display_panel_handle = {};

static void Display_spi_cmd(uint8_t cmd) {
    struct spi_transaction_t txn = (spi_transaction_t){ .cmd = 0U, .addr = cmd, .length = 0, .rxlength = 0 };
    spi_device_transmit(Display_spi_handle, &txn);
}

static void Display_spi_data(uint8_t data) {
    struct spi_transaction_t txn = (spi_transaction_t){ .cmd = 1U, .addr = data, .length = 0, .rxlength = 0 };
    spi_device_transmit(Display_spi_handle, &txn);
}

static void Display_cs_enable(void) {
    TCA9554_set_pin(3, false);
    vTaskDelay(pdMS_TO_TICKS(10));
}

static void Display_cs_disable(void) {
    TCA9554_set_pin(3, true);
    vTaskDelay(pdMS_TO_TICKS(10));
}

static void Display_reset(void) {
    TCA9554_set_pin(1, false);
    vTaskDelay(pdMS_TO_TICKS(10));
    TCA9554_set_pin(1, true);
    vTaskDelay(pdMS_TO_TICKS(50));
}

static void Display_spi_init(void) {
    spi_bus_config_t buscfg = (spi_bus_config_t){ .mosi_io_num = 1, .miso_io_num = -1, .sclk_io_num = 2, .quadwp_io_num = -1, .quadhd_io_num = -1, .max_transfer_sz = 64 };
    spi_bus_initialize(SPI2_HOST, &buscfg, SPI_DMA_CH_AUTO);
    spi_device_interface_config_t devcfg = (spi_device_interface_config_t){ .command_bits = 1U, .address_bits = 8U, .mode = 0U, .clock_speed_hz = 40000000, .spics_io_num = -1, .queue_size = 1 };
    spi_bus_add_device(SPI2_HOST, &devcfg, &Display_spi_handle);
}

static void Display_st7701_init(void) {
    Display_cs_enable();
    Display_spi_cmd(0xFF);
    Display_spi_data(0x77);
    Display_spi_data(0x01);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x10);
    Display_spi_cmd(0xC0);
    Display_spi_data(0x3B);
    Display_spi_data(0x00);
    Display_spi_cmd(0xC1);
    Display_spi_data(0x0B);
    Display_spi_data(0x02);
    Display_spi_cmd(0xC2);
    Display_spi_data(0x07);
    Display_spi_data(0x02);
    Display_spi_cmd(0xCC);
    Display_spi_data(0x10);
    Display_spi_cmd(0xCD);
    Display_spi_data(0x08);
    Display_spi_cmd(0xB0);
    Display_spi_data(0x00);
    Display_spi_data(0x11);
    Display_spi_data(0x16);
    Display_spi_data(0x0e);
    Display_spi_data(0x11);
    Display_spi_data(0x06);
    Display_spi_data(0x05);
    Display_spi_data(0x09);
    Display_spi_data(0x08);
    Display_spi_data(0x21);
    Display_spi_data(0x06);
    Display_spi_data(0x13);
    Display_spi_data(0x10);
    Display_spi_data(0x29);
    Display_spi_data(0x31);
    Display_spi_data(0x18);
    Display_spi_cmd(0xB1);
    Display_spi_data(0x00);
    Display_spi_data(0x11);
    Display_spi_data(0x16);
    Display_spi_data(0x0e);
    Display_spi_data(0x11);
    Display_spi_data(0x07);
    Display_spi_data(0x05);
    Display_spi_data(0x09);
    Display_spi_data(0x09);
    Display_spi_data(0x21);
    Display_spi_data(0x05);
    Display_spi_data(0x13);
    Display_spi_data(0x11);
    Display_spi_data(0x2a);
    Display_spi_data(0x31);
    Display_spi_data(0x18);
    Display_spi_cmd(0xFF);
    Display_spi_data(0x77);
    Display_spi_data(0x01);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x11);
    Display_spi_cmd(0xB0);
    Display_spi_data(0x6d);
    Display_spi_cmd(0xB1);
    Display_spi_data(0x37);
    Display_spi_cmd(0xB2);
    Display_spi_data(0x81);
    Display_spi_cmd(0xB3);
    Display_spi_data(0x80);
    Display_spi_cmd(0xB5);
    Display_spi_data(0x43);
    Display_spi_cmd(0xB7);
    Display_spi_data(0x85);
    Display_spi_cmd(0xB8);
    Display_spi_data(0x20);
    Display_spi_cmd(0xC1);
    Display_spi_data(0x78);
    Display_spi_cmd(0xC2);
    Display_spi_data(0x78);
    Display_spi_cmd(0xD0);
    Display_spi_data(0x88);
    Display_spi_cmd(0xE0);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x02);
    Display_spi_cmd(0xE1);
    Display_spi_data(0x03);
    Display_spi_data(0xA0);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x04);
    Display_spi_data(0xA0);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x20);
    Display_spi_data(0x20);
    Display_spi_cmd(0xE2);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_cmd(0xE3);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x11);
    Display_spi_data(0x00);
    Display_spi_cmd(0xE4);
    Display_spi_data(0x22);
    Display_spi_data(0x00);
    Display_spi_cmd(0xE5);
    Display_spi_data(0x05);
    Display_spi_data(0xEC);
    Display_spi_data(0xA0);
    Display_spi_data(0xA0);
    Display_spi_data(0x07);
    Display_spi_data(0xEE);
    Display_spi_data(0xA0);
    Display_spi_data(0xA0);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_cmd(0xE6);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x11);
    Display_spi_data(0x00);
    Display_spi_cmd(0xE7);
    Display_spi_data(0x22);
    Display_spi_data(0x00);
    Display_spi_cmd(0xE8);
    Display_spi_data(0x06);
    Display_spi_data(0xED);
    Display_spi_data(0xA0);
    Display_spi_data(0xA0);
    Display_spi_data(0x08);
    Display_spi_data(0xEF);
    Display_spi_data(0xA0);
    Display_spi_data(0xA0);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_cmd(0xEB);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x40);
    Display_spi_data(0x40);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_cmd(0xED);
    Display_spi_data(0xFF);
    Display_spi_data(0xFF);
    Display_spi_data(0xFF);
    Display_spi_data(0xBA);
    Display_spi_data(0x0A);
    Display_spi_data(0xBF);
    Display_spi_data(0x45);
    Display_spi_data(0xFF);
    Display_spi_data(0xFF);
    Display_spi_data(0x54);
    Display_spi_data(0xFB);
    Display_spi_data(0xA0);
    Display_spi_data(0xAB);
    Display_spi_data(0xFF);
    Display_spi_data(0xFF);
    Display_spi_data(0xFF);
    Display_spi_cmd(0xEF);
    Display_spi_data(0x10);
    Display_spi_data(0x0D);
    Display_spi_data(0x04);
    Display_spi_data(0x08);
    Display_spi_data(0x3F);
    Display_spi_data(0x1F);
    Display_spi_cmd(0xFF);
    Display_spi_data(0x77);
    Display_spi_data(0x01);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x13);
    Display_spi_cmd(0xEF);
    Display_spi_data(0x08);
    Display_spi_cmd(0xFF);
    Display_spi_data(0x77);
    Display_spi_data(0x01);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_data(0x00);
    Display_spi_cmd(0x36);
    Display_spi_data(0x00);
    Display_spi_cmd(0x3A);
    Display_spi_data(0x66);
    Display_spi_cmd(0x11);
    vTaskDelay(pdMS_TO_TICKS(480));
    Display_spi_cmd(0x20);
    vTaskDelay(pdMS_TO_TICKS(120));
    Display_spi_cmd(0x29);
    Display_cs_disable();
}

static void Display_rgb_panel_init(void) {
    esp_lcd_rgb_panel_config_t rgb_config = (esp_lcd_rgb_panel_config_t){ .clk_src = LCD_CLK_SRC_PLL160M, .timings = (esp_lcd_rgb_timing_t){ .pclk_hz = 16000000, .h_res = 480, .v_res = 480, .hsync_pulse_width = 8, .hsync_back_porch = 10, .hsync_front_porch = 50, .vsync_pulse_width = 3, .vsync_back_porch = 8, .vsync_front_porch = 8 }, .data_width = 16, .psram_trans_align = 64, .hsync_gpio_num = 38, .vsync_gpio_num = 39, .de_gpio_num = 40, .pclk_gpio_num = 41, .data_gpio_nums = {5, 45, 48, 47, 21, 14, 13, 12, 11, 10, 9, 46, 3, 8, 18, 17}, .disp_gpio_num = -1 };
    rgb_config.flags.fb_in_psram = true;
    esp_lcd_new_rgb_panel(&rgb_config, &Display_panel_handle);
    esp_lcd_panel_reset(Display_panel_handle);
    esp_lcd_panel_init(Display_panel_handle);
}

static void Display_backlight_init(void) {
    ledcSetup(0, 20000, 10);
    ledcAttachPin(6, 0);
    ledcWrite(0, 500);
}

void Display_init(void) {
    Display_reset();
    Display_spi_init();
    Display_st7701_init();
    Display_rgb_panel_init();
    Display_backlight_init();
}

void Display_fill_color(uint16_t color) {
    uint16_t buf[480] = {0};
    uint32_t i = 0U;
    while (i < 480) {
        buf[i] = color;
        i = i + 1U;
    }
    i = 0U;
    while (i < 480) {
        esp_lcd_panel_draw_bitmap(Display_panel_handle, 0, i, 480, i + 1, buf);
        i = i + 1U;
    }
}
