/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "gauge_speed.hpp"

#include <lvgl.h>
#include "lvgl_helpers.h"
#include "needle_img.h"

#include <stdint.h>
#include <stdbool.h>

/* Scope: GaugeSpeed */
static lv_obj_handle_t GaugeSpeed_scale = {};
static lv_obj_handle_t GaugeSpeed_needle = {};
static lv_obj_handle_t GaugeSpeed_speed_label = {};
static lv_obj_handle_t GaugeSpeed_arc = {};

static void GaugeSpeed_on_arc_changed(lv_event_t* e) {
    lv_obj_t* target = lv_event_get_target_obj(e);
    int32_t speed = lv_arc_get_value(target);
    lv_scale_set_image_needle_value(GaugeSpeed_scale, GaugeSpeed_needle, speed);
    lvgl_helper_label_set_speed(GaugeSpeed_speed_label, speed);
}

void GaugeSpeed_create(void) {
    lv_obj_t* scr = lv_screen_active();
    lvgl_helper_obj_style_bg_color_hex(scr, 0x1A1A2EU, LV_PART_MAIN);
    GaugeSpeed_scale = lv_scale_create(scr);
    lv_obj_set_size(GaugeSpeed_scale, 420, 420);
    lv_obj_center(GaugeSpeed_scale);
    lvgl_helper_scale_set_round_inner(GaugeSpeed_scale);
    lv_scale_set_range(GaugeSpeed_scale, 0, 85);
    lv_scale_set_angle_range(GaugeSpeed_scale, 270U);
    lv_scale_set_rotation(GaugeSpeed_scale, 135);
    lv_scale_set_total_tick_count(GaugeSpeed_scale, 18U);
    lv_scale_set_major_tick_every(GaugeSpeed_scale, 2U);
    lv_scale_set_label_show(GaugeSpeed_scale, true);
    lv_obj_set_style_length(GaugeSpeed_scale, 12, LV_PART_ITEMS);
    lv_obj_set_style_line_width(GaugeSpeed_scale, 2, LV_PART_ITEMS);
    lvgl_helper_obj_style_line_color_hex(GaugeSpeed_scale, 0xCCCCCCU, LV_PART_ITEMS);
    lv_obj_set_style_length(GaugeSpeed_scale, 20, LV_PART_INDICATOR);
    lv_obj_set_style_line_width(GaugeSpeed_scale, 3, LV_PART_INDICATOR);
    lvgl_helper_obj_style_line_color_hex(GaugeSpeed_scale, 0xFFFFFFU, LV_PART_INDICATOR);
    lvgl_helper_obj_style_text_color_hex(GaugeSpeed_scale, 0xFFFFFFU, LV_PART_INDICATOR);
    lvgl_helper_obj_style_text_font_24(GaugeSpeed_scale, LV_PART_INDICATOR);
    lvgl_helper_add_speed_sections(GaugeSpeed_scale);
    lv_obj_set_style_bg_opa(GaugeSpeed_scale, LV_OPA_COVER, LV_PART_MAIN);
    lvgl_helper_obj_style_bg_color_hex(GaugeSpeed_scale, 0x1A1A2EU, LV_PART_MAIN);
    lv_obj_set_style_radius(GaugeSpeed_scale, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    GaugeSpeed_needle = lvgl_helper_create_needle_img(GaugeSpeed_scale);
    GaugeSpeed_speed_label = lv_label_create(scr);
    lvgl_helper_label_set_speed(GaugeSpeed_speed_label, 0);
    lv_obj_align(GaugeSpeed_speed_label, LV_ALIGN_CENTER, 0, 120);
    lvgl_helper_obj_style_text_font_40(GaugeSpeed_speed_label, LV_PART_MAIN);
    lvgl_helper_obj_style_text_color_hex(GaugeSpeed_speed_label, 0xFFFFFFU, LV_PART_MAIN);
    GaugeSpeed_arc = lv_arc_create(scr);
    lv_obj_set_size(GaugeSpeed_arc, 420, 420);
    lv_obj_center(GaugeSpeed_arc);
    lv_arc_set_range(GaugeSpeed_arc, 0, 85);
    lv_arc_set_value(GaugeSpeed_arc, 0);
    lv_arc_set_bg_angles(GaugeSpeed_arc, 0, 270);
    lv_arc_set_rotation(GaugeSpeed_arc, 135);
    lv_obj_set_style_arc_opa(GaugeSpeed_arc, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_arc_opa(GaugeSpeed_arc, LV_OPA_TRANSP, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(GaugeSpeed_arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_add_event_cb(GaugeSpeed_arc, GaugeSpeed_on_arc_changed, LV_EVENT_VALUE_CHANGED, 0);
    lv_scale_set_image_needle_value(GaugeSpeed_scale, GaugeSpeed_needle, 0);
}
