/**
 * Generated by C-Next Transpiler from: gauge_speed.cnx
 * A safer C for embedded systems
 */

#include "gauge_speed.hpp"

#include <lvgl.h>
#include "needle_img.hpp"
#include "needle_img_boundary.h"

#include <stdint.h>
#include <stdbool.h>

/* Scope: GaugeSpeed */
static lv_obj_t* GaugeSpeed_scale = NULL;
static lv_obj_t* GaugeSpeed_needle = NULL;
static lv_obj_t* GaugeSpeed_speed_label = NULL;
static lv_obj_t* GaugeSpeed_arc = NULL;
static lv_style_t GaugeSpeed_green_main = {0};
static lv_style_t GaugeSpeed_green_ind = {0};
static lv_style_t GaugeSpeed_green_items = {0};
static lv_style_t GaugeSpeed_orange_main = {0};
static lv_style_t GaugeSpeed_orange_ind = {0};
static lv_style_t GaugeSpeed_orange_items = {0};

static void GaugeSpeed_on_arc_changed(lv_event_t* e) {
    lv_obj_t* target = lv_event_get_target_obj(e);
    int32_t speed = lv_arc_get_value(target);
    lv_scale_set_image_needle_value(GaugeSpeed_scale, GaugeSpeed_needle, speed);
    lv_label_set_text_fmt(GaugeSpeed_speed_label, "%d mph", speed);
}

void GaugeSpeed_create(void) {
    lv_obj_t* scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_hex(0x1A1A2E), LV_PART_MAIN);
    GaugeSpeed_scale = lv_scale_create(scr);
    lv_obj_set_size(GaugeSpeed_scale, 420, 420);
    lv_obj_center(GaugeSpeed_scale);
    lv_scale_set_mode(GaugeSpeed_scale, LV_SCALE_MODE_ROUND_INNER);
    lv_scale_set_range(GaugeSpeed_scale, 0, 85);
    lv_scale_set_angle_range(GaugeSpeed_scale, 270);
    lv_scale_set_rotation(GaugeSpeed_scale, 135);
    lv_scale_set_total_tick_count(GaugeSpeed_scale, 18);
    lv_scale_set_major_tick_every(GaugeSpeed_scale, 2);
    lv_scale_set_label_show(GaugeSpeed_scale, true);
    lv_obj_set_style_length(GaugeSpeed_scale, 12, LV_PART_ITEMS);
    lv_obj_set_style_line_width(GaugeSpeed_scale, 2, LV_PART_ITEMS);
    lv_obj_set_style_line_color(GaugeSpeed_scale, lv_color_hex(0xCCCCCC), LV_PART_ITEMS);
    lv_obj_set_style_length(GaugeSpeed_scale, 20, LV_PART_INDICATOR);
    lv_obj_set_style_line_width(GaugeSpeed_scale, 3, LV_PART_INDICATOR);
    lv_obj_set_style_line_color(GaugeSpeed_scale, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR);
    lv_obj_set_style_text_color(GaugeSpeed_scale, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR);
    lv_obj_set_style_text_font(GaugeSpeed_scale, &lv_font_montserrat_24, LV_PART_INDICATOR);
    lv_style_init(&GaugeSpeed_green_main);
    lv_style_set_arc_color(&GaugeSpeed_green_main, lv_color_hex(0x44BB44));
    lv_style_set_arc_width(&GaugeSpeed_green_main, 8);
    lv_style_init(&GaugeSpeed_green_ind);
    lv_style_set_line_color(&GaugeSpeed_green_ind, lv_color_hex(0x44BB44));
    lv_style_init(&GaugeSpeed_green_items);
    lv_style_set_line_color(&GaugeSpeed_green_items, lv_color_hex(0x44BB44));
    lv_scale_section_t* green_sec = lv_scale_add_section(GaugeSpeed_scale);
    lv_scale_set_section_range(GaugeSpeed_scale, green_sec, 0, 80);
    lv_scale_set_section_style_main(GaugeSpeed_scale, green_sec, &GaugeSpeed_green_main);
    lv_scale_set_section_style_indicator(GaugeSpeed_scale, green_sec, &GaugeSpeed_green_ind);
    lv_scale_set_section_style_items(GaugeSpeed_scale, green_sec, &GaugeSpeed_green_items);
    lv_style_init(&GaugeSpeed_orange_main);
    lv_style_set_arc_color(&GaugeSpeed_orange_main, lv_color_hex(0xFF8C00));
    lv_style_set_arc_width(&GaugeSpeed_orange_main, 8);
    lv_style_init(&GaugeSpeed_orange_ind);
    lv_style_set_line_color(&GaugeSpeed_orange_ind, lv_color_hex(0xFF8C00));
    lv_style_init(&GaugeSpeed_orange_items);
    lv_style_set_line_color(&GaugeSpeed_orange_items, lv_color_hex(0xFF8C00));
    lv_scale_section_t* orange_sec = lv_scale_add_section(GaugeSpeed_scale);
    lv_scale_set_section_range(GaugeSpeed_scale, orange_sec, 80, 85);
    lv_scale_set_section_style_main(GaugeSpeed_scale, orange_sec, &GaugeSpeed_orange_main);
    lv_scale_set_section_style_indicator(GaugeSpeed_scale, orange_sec, &GaugeSpeed_orange_ind);
    lv_scale_set_section_style_items(GaugeSpeed_scale, orange_sec, &GaugeSpeed_orange_items);
    lv_obj_set_style_bg_opa(GaugeSpeed_scale, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_bg_color(GaugeSpeed_scale, lv_color_hex(0x1A1A2E), LV_PART_MAIN);
    lv_obj_set_style_radius(GaugeSpeed_scale, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    GaugeSpeed_needle = lvgl_helper_create_needle_img(GaugeSpeed_scale);
    GaugeSpeed_speed_label = lv_label_create(scr);
    lv_label_set_text_fmt(GaugeSpeed_speed_label, "%d mph", 0);
    lv_obj_align(GaugeSpeed_speed_label, LV_ALIGN_CENTER, 0, 120);
    lv_obj_set_style_text_font(GaugeSpeed_speed_label, &lv_font_montserrat_40, LV_PART_MAIN);
    lv_obj_set_style_text_color(GaugeSpeed_speed_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    GaugeSpeed_arc = lv_arc_create(scr);
    lv_obj_set_size(GaugeSpeed_arc, 420, 420);
    lv_obj_center(GaugeSpeed_arc);
    lv_arc_set_range(GaugeSpeed_arc, 0, 85);
    lv_arc_set_value(GaugeSpeed_arc, 0);
    lv_arc_set_bg_angles(GaugeSpeed_arc, 0, 270);
    lv_arc_set_rotation(GaugeSpeed_arc, 135);
    lv_obj_set_style_arc_opa(GaugeSpeed_arc, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_arc_opa(GaugeSpeed_arc, LV_OPA_TRANSP, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(GaugeSpeed_arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_add_event_cb(GaugeSpeed_arc, GaugeSpeed_on_arc_changed, LV_EVENT_VALUE_CHANGED, 0);
    lv_scale_set_image_needle_value(GaugeSpeed_scale, GaugeSpeed_needle, 0);
}
