#ifndef LVGL_PORT_H
#define LVGL_PORT_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "display_st7701.hpp"
#include "touch_cst820.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void LvglPort_init(void);
void LvglPort_create_demo_label(void);
void LvglPort_loop(void);

#ifdef __cplusplus
}
#endif

#endif /* LVGL_PORT_H */
