/**
 * Generated by C-Next Transpiler from: lvgl_port.cnx
 * A safer C for embedded systems
 */

#include "lvgl_port.hpp"

#include "display_st7701.hpp"
#include "touch_cst820.hpp"
#include <lvgl.h>
#include <Arduino.h>
#include <esp_lcd_panel_ops.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: LvglPort */
static uint8_t LvglPort_buf1[46080] = {0};
static uint8_t LvglPort_buf2[46080] = {0};
static uint32_t LvglPort_last_tick = 0;
static esp_lcd_panel_handle_t LvglPort_panel = {};

static void LvglPort_disp_flush(lv_display_t* disp, const lv_area_t* area, uint8_t* px_map) {
    int32_t x2_end = area->x2 + 1;
    int32_t y2_end = area->y2 + 1;
    esp_lcd_panel_draw_bitmap(LvglPort_panel, area->x1, area->y1, x2_end, y2_end, px_map);
    lv_display_flush_ready(disp);
}

static void LvglPort_touch_read(lv_indev_t* indev, lv_indev_data_t* data) {
    bool touched = Touch_read();
    if (touched == true) {
        data->point.x = Touch_get_x();
        data->point.y = Touch_get_y();
        data->state = LV_INDEV_STATE_PRESSED;
    } else {
        data->state = LV_INDEV_STATE_RELEASED;
    }
}

void LvglPort_init(void) {
    LvglPort_panel = Display_get_panel();
    lv_display_t* disp = lv_display_create(480, 480);
    lv_display_set_buffers(disp, LvglPort_buf1, LvglPort_buf2, 46080, LV_DISPLAY_RENDER_MODE_PARTIAL);
    lv_display_set_flush_cb(disp, LvglPort_disp_flush);
    lv_indev_t* indev = lv_indev_create();
    lv_indev_set_type(indev, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(indev, LvglPort_touch_read);
    LvglPort_last_tick = millis();
}

void LvglPort_loop(void) {
    uint32_t now = millis();
    uint32_t elapsed = now - LvglPort_last_tick;
    LvglPort_last_tick = now;
    lv_tick_inc(elapsed);
    lv_timer_handler();
}
