/**
 * Generated by C-Next Transpiler from: main.cnx
 * A safer C for embedded systems
 */

#include <Arduino.h>
#include <lvgl.h>
#include "display/display_st7701.hpp"
#include "display/touch_cst820.hpp"
#include "display/lvgl_port.hpp"
#include "display/gauge_temp.hpp"
#include "data/can_bus.hpp"

void setup(void) {
    Serial.begin(115200);
    Serial.println("OGauge: Signal Catalog");
    Serial.println("I2C init...");
    I2C_init();
    Serial.println("TCA9554 init...");
    TCA9554_init(0x00);
    Serial.println("Display init...");
    Display_init();
    Serial.println("Touch init...");
    Touch_init();
    Serial.println("LVGL init...");
    lv_init();
    LvglPort_init();
    Serial.println("Gauge init...");
    GaugeTemp_create();
    Serial.println("CAN init...");
    CanBus_init();
    Serial.println("Ready!");
}

void loop(void) {
    CanBus_poll();
    LvglPort_loop();
    delay(5);
}
