#ifndef MAIN_H
#define MAIN_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "display_st7701.hpp"
#include "touch_cst820.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint16_t COLOR_BLUE;
extern const uint16_t COLOR_RED;
extern const uint16_t COLOR_WHITE;
extern const uint32_t NUM_COLORS;
extern uint16_t colors[3];
extern uint32_t color_index;

#ifdef __cplusplus
}
#endif

#endif /* MAIN_H */
