/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "touch_cst820.h"

#include "tca9554.h"
#include <Arduino.h>
#include <Wire.h>

#include <stdint.h>
#include <stdbool.h>

/* Scope: Touch */
static uint8_t Touch_points = 0;
static uint16_t Touch_x = 0;
static uint16_t Touch_y = 0;

static void Touch_reset(void) {
    TCA9554_set_pin(2, false);
    delay(10);
    TCA9554_set_pin(2, true);
    delay(50);
}

void Touch_init(void) {
    Touch_reset();
    I2C_write_byte(0x15, 0xFE, 0xFF);
    Serial.println("Touch: CST820 initialized");
}

bool Touch_read(void) {
    Wire.beginTransmission(0x15);
    Wire.write(0x01);
    Wire.endTransmission(false);
    Wire.requestFrom(0x15, 6);
    uint8_t gesture = Wire.read();
    Touch_points = Wire.read();
    uint8_t x_hi = Wire.read();
    uint8_t x_lo = Wire.read();
    uint8_t y_hi = Wire.read();
    uint8_t y_lo = Wire.read();
    uint16_t x_high = x_hi & 0x0FU;
    uint16_t y_high = y_hi & 0x0FU;
    Touch_x = (x_high << 8U) | x_lo;
    Touch_y = (y_high << 8U) | y_lo;
    return (Touch_points > 0);
}

uint16_t Touch_get_x(void) {
    return Touch_x;
}

uint16_t Touch_get_y(void) {
    return Touch_y;
}
