#ifndef GAUGE_TRANS_H
#define GAUGE_TRANS_H

/**
 * Generated by C-Next Transpiler from: gauge_trans.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../data/signal_data.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void GaugeTrans_update(void);
void GaugeTrans_create(void);

#ifdef __cplusplus
}
#endif

#endif /* GAUGE_TRANS_H */
