#ifndef GAUGE_TEMP_H
#define GAUGE_TEMP_H

/**
 * Generated by C-Next Transpiler from: gauge_temp.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "../data/signal_data.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void GaugeTemp_update(void);
void GaugeTemp_create(void);

#ifdef __cplusplus
}
#endif

#endif /* GAUGE_TEMP_H */
