#ifndef I2C_DRIVER_H
#define I2C_DRIVER_H

/**
 * Generated by C-Next Transpiler from: i2c_driver.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void I2C_init(void);
uint8_t I2C_read_byte(uint8_t addr, uint8_t reg);
bool I2C_write_byte(uint8_t addr, uint8_t reg, uint8_t data);

#ifdef __cplusplus
}
#endif

#endif /* I2C_DRIVER_H */
