#ifndef NEEDLE_IMG_H
#define NEEDLE_IMG_H

/**
 * Generated by C-Next Transpiler from: needle_img.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const int32_t NeedleImg_W;
extern const int32_t NeedleImg_H;
extern const int32_t NeedleImg_PIVOT_X;
extern const int32_t NeedleImg_PIVOT_Y;
extern uint8_t NeedleImg_map[14400];
extern lv_image_dsc_t NeedleImg_dsc;

#ifdef __cplusplus
}
#endif

#endif /* NEEDLE_IMG_H */
