#ifndef TCA9554_H
#define TCA9554_H

/**
 * Generated by C-Next Transpiler from: tca9554.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "i2c_driver.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void TCA9554_init(uint8_t pin_modes);
void TCA9554_set_pin(uint8_t pin, bool state);
bool TCA9554_read_pin(uint8_t pin);

#ifdef __cplusplus
}
#endif

#endif /* TCA9554_H */
