/**
 * Generated by C-Next Transpiler from: signal_data.cnx
 * A safer C for embedded systems
 */

#include "data/signal_data.hpp"

#include <stdint.h>

// Signal value + timestamp pair
// Written by J1939 decoder, read by display widgets
// ETC2 gear state — three raw bytes from PGN 61445 (SA 3 / TCM).
// Display renders each via GaugeTrans.gear_char/lever_char; kept raw here so
// all character logic lives in one place (the UI), not split into the decoder.
// J1939 2-bit telltale state: 0=off 1=on 2=error 3=N/A
// All known signal values in native J1939 units
// Unit conversion (kPa→PSI, C→F) happens at display time
extern const uint32_t SIGNAL_STALE_MS = 2000U;

/* Scope: SignalStore */
SignalData SignalStore_current = {};
