/**
 * Generated by C-Next Transpiler from: signal_data.cnx
 * A safer C for embedded systems
 */

#include "data/signal_data.hpp"

#include <stdint.h>

// Signal value + timestamp pair
// Written by J1939 decoder, read by display widgets
// All known signal values in native J1939 units
// Unit conversion (kPa→PSI, C→F) happens at display time
extern const uint32_t SIGNAL_STALE_MS = 2000U;

/* Scope: SignalStore */
SignalData SignalStore_current = {0};
